"""Shared dimensions used by both top-level pages."""

WINDOW_WIDTH = 430
WINDOW_HEIGHT = 420
WINDOW_MIN_WIDTH = 360
WINDOW_MIN_HEIGHT = 360
CARD_RADIUS = 14
CONTROL_HEIGHT = 36
ICON_BUTTON_SIZE = 32
TAB_HEIGHT = 38
PAGE_MARGIN = 0
SECTION_SPACING = 6
